version: '3.1'

services:
  plumber_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - plumber_lan

networks:
  plumber_lan:
      driver: bridge

